FROM ghcr.io/nuvolaris/nuvolaris-devkit:neo-2021.1218.1845
RUN curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
RUN git clone https://github.com/apache/openwhisk-deploy-kube /home/nuvolaris/openwhisk-deploy-kube
